sensible error when we don't have permission to attach to the process
git-svn-id: svn://svn.debian.org/svn/pkg-samba/trunk@489 fc4039ab-9d04-0410-8cac-899223bdd6b0

diff --git a/panic-action b/panic-action
--- a/panic-action
+++ b/panic-action
@@ -21,6 +21,14 @@
 	echo "was called for pid $1 ($BINARYNAME)."
 	echo
 
+	if [ -z "$BINARYNAME" ]; then
+		echo "This means there was a problem with the program, such as a segfault."
+		echo "However, the executable could not be found for process $1."
+		echo "It may have died unexpectedly, or you may not have permission to"
+		echo "debug the process."
+		exit 1
+	fi
+
 	# No debugger
 	if [ ! -x /usr/bin/gdb ]; then
 		echo "This means there was a problem with the program, such as a segfault."
